/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.tomaszmichalak.example.azurepipelines;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
